IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/MahalanobisAD_SubSeq/frame64_3/extraction_features'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/CenterLossVAE/ex15_subseq'
  
param:
  # dataloader
  batch_size : 512
  shuffle : True
  # train
  num_epochs : 30
  # latent_size
  mid_size : 256
  latent_size : 256
  # etc
  devise : 'cuda'
  max_fpr : 0.1
