IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/timm_EfficientnetB4/extraction_features'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/CenterLossVAE/efficientnet/ex21'
  
param:
  # dataloader
  batch_size : 1024
  shuffle : True
  # train
  num_epochs : 300
  # latent_size
  mid_size : 2048
  latent_size : 2048
  # etc
  devise : 'cuda'
  max_fpr : 0.1
