IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/datasets_add/dev_data'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/PaDiM/ex1'
  PREMODEL_ROOT: '/home/hiroki/research/dcase2021_task2/input/PANNs/pre_trained_model/Cnn14_16k_mAP=0.438.pth'

param:
  # feature
  sample_rate: 16000
  window_size: 512
  hop_size: 160
  mel_bins: 64
  fmin: 50
  fmax: 8000
  # dataloader
  batch_size : 64
  shuffle : False
  num_epochs : 1
  # etc
  devise : 'cuda'
  max_fpr : 0.1
