IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/MahalanobisAD_orig_add_data_32k_revised/extraction_features'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/CenterLossVAE/ex19'
  
param:
  # dataloader
  batch_size : 512
  shuffle : True
  # train
  num_epochs : 100
  # latent_size
  mid_size : 2048
  latent_size : 2048
  # etc
  devise : 'cuda'
  max_fpr : 0.1
