IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/datasets'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/PANNs_wavegram'
  PREMODEL_ROOT: '/home/hiroki/research/dcase2021_task2/input/PANNs/pre_trained_model/Wavegram_Cnn14_mAP=0.389.pth'
  
param:
  # feature
  sample_rate: 32000
  window_size: 1024
  hop_size: 320
  mel_bins: 64
  fmin: 50
  fmax: 14000
  # dataloader
  batch_size : 90
  shuffle : False
  num_epochs : 1
  # etc
  devise : 'cuda'
  max_fpr : 0.1
