dev_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/datasets/dev_data
add_dev_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/datasets/add_dev_data
eval_directory: ../eval_data
model_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/output/SubSeq_Approach/baseline_mobilenet/model
result_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/output/SubSeq_Approach/baseline_mobilenet/result
result_file: result.csv

max_fpr: 0.1
decision_threshold: 0.9
ext: wav

feature:
  n_mels: 128
  n_frames: 64
  n_hop_frames: 8
  n_fft: 1024
  hop_length: 512
  power: 2.0

training:
  learning_rate: 0.00001
  epochs : 20
  batch_size : 32
  shuffle : True
  validation_split : 0.1
  weight_decay: 0.0
  lr_step_size: 50
  lr_gamma: 0.5
  verbose : 1
