IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/datasets'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/CNN_finetune_ex2'
  PREMODEL_ROOT: '/home/hiroki/research/dcase2021_task2/input/PANNs/pre_trained_model/ResNet38_mAP=0.434.pth'
  
param:
  # feature
  n_mels: 128
  n_frames: 64
  n_hop_frames: 8
  n_fft: 1024
  hop_length: 512
  power: 2.0
  # dataloader
  batch_size : 64
  shuffle : True
  # train
  num_epochs : 100
  # etc
  devise : 'cuda'
  max_fpr : 0.1
