IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/MahalanobisAD_orig_add_data_32k/extraction_features'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/ID_Conditional_VAE/VAE'
  
param:
  # dataloader
  batch_size : 256
  shuffle : True
  # train
  num_epochs : 100
  # latent_size
  mid_size : 1024
  latent_size : 64
  # etc
  devise : 'cuda'
  max_fpr : 0.1
