dev_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/datasets_add/dev_data
#eval_directory: ../eval_data
model_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/output/baseline_centerloss_VAE/model
result_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/output/baseline_centerloss_VAE/result
tensorboard_directory: /media/hiroki/HDD1TB/research/dcase2021_task2/output/baseline_centerloss_VAE/tensorboard
result_file: result.csv

max_fpr: 0.1
decision_threshold: 0.9
ext: wav

feature:
  n_mels: 128
  n_frames: 5
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

model:
  hidden_dim: 256
  latent_dim: 128
  n_hidden: 3

training:
  learning_rate: 0.001
  epochs : 50
  batch_size : 2048
  shuffle : True
  validation_split : 0.0
  weight_decay: 0.0
  lr_step_size: 50
  lr_gamma: 0.5
  verbose : 1

etc:
  debug : False